
import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
"""
check_nontext_facts.py — Readability Audit Skill  v2
Systematically audits ALL non-text media types in a page's raw HTML and
classifies them by accessibility quality for AI crawlers.

Categories audited (W3C / HTML5 spec):
  1. standard_images    — <img> and <picture>/<source> elements
  2. vector_graphics    — inline <svg> elements
  3. embedded_media     — <video>, <audio>, <iframe> (YouTube / Vimeo / generic)
  4. canvas_interactive — <canvas> elements
  5. icon_elements      — icon fonts / sprite elements (<i class="">, role="img" spans)
  6. linked_documents   — linked .pdf files (byte-header text-layer heuristic)

Zero external dependencies — standard library only (html.parser, re, urllib.parse).
"""

import sys
import json

# --- robots.txt gate --------------------------------------------------------
# Every fetch in this file asks robots_gate first. The gate is built from the
# robots.txt that check_robots.py already fetched (passed in as `robots`), so
# it costs no extra request; only a standalone run fetches robots.txt itself.
import os as _os
for _d in (_os.path.dirname(_os.path.abspath(__file__)),
           _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                         "..", "..", "crawl-access-audit", "scripts")):
    if _d not in sys.path:
        sys.path.insert(0, _d)
try:
    from robots_gate import RobotsGate
except Exception:  # gate unavailable -> refuse to fetch, never fetch blind
    RobotsGate = None

import re
import io
import os
import time
import zlib
import urllib.request
import urllib.parse
import urllib.error
from html.parser import HTMLParser

# ---------------------------------------------------------------------------
# Generic / placeholder alt-text terms (case-insensitive exact match)
# ---------------------------------------------------------------------------
GENERIC_ALT_TERMS = {
    "image", "photo", "picture", "banner", "logo", "icon", "graphic",
    "img", "placeholder", "untitled", "thumbnail", "figure", "screenshot",
    "test", "temp", "default", "hero", "header image", "cover", "cover image",
    "spacer", "divider", "blank", "no image", "n/a",
}

# A single generic word optionally followed by a number/letter suffix
# ("image", "photo 2", "banner-3", "img_04", "picture (1)") -- replaces the old
# enumerated "image 1 / image 2 / image 3" entries with one pattern.
GENERIC_ALT_RX = re.compile(
    r"^(image|images|photo|photos|picture|pic|pics|banner|logo|icon|graphic|"
    r"img|figure|fig|thumbnail|thumb|screenshot|slide|item|product|gallery)"
    r"[\s._\-]*\(?\d*\)?[a-z]?$",
    re.I,
)

# Auto-generated / camera / CMS-export filename stems (no extension, lowercased).
# Detects names that carry no descriptive information regardless of the alt text.
_AUTOGEN_FILENAME_RX = re.compile(
    r"^("
    r"(img|image|images|dsc|dscn|dscf|pxl|gopr|mvimg|pano|photo|pic|scan|scanned|"
    r"capture|screenshot|screen[\s._-]?shot|screen[\s._-]?capture|snip|snap|"
    r"untitled|unnamed|noname|new|final|final2|finalfinal|copy|copyof|draft|"
    r"download|downloaded|file|files|upload|uploaded|attachment|asset|assets|"
    r"hero|banner|bg|background|placeholder|temp|tmp|test|output|export|render)"
    r"[\s._\-]*\(?\d*\)?"
    r"|\d{3,}"                              # 1633024800  (timestamps / ids)
    r"|[0-9a-f]{8,}"                        # deadbeefcafe (hex hashes)
    r"|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"  # uuid
    r"|[a-z0-9]{20,}"                       # long CMS content hashes
    r")$",
    re.I,
)


def _filename_stem(src: str) -> str:
    if not src:
        return ""
    path = src.split("?")[0].split("#")[0]
    base = path.rstrip("/").split("/")[-1]
    if "." in base:
        base = base.rsplit(".", 1)[0]
    return base.strip()


def _is_autogenerated_filename(src: str) -> bool:
    stem = _filename_stem(src)
    if not stem or len(stem) < 3:
        return False
    return bool(_AUTOGEN_FILENAME_RX.match(stem))

# Icon-font class fragments that indicate a decorative/icon element
ICON_CLASS_FRAGMENTS = (
    "fa-", "fa ", "fas ", "far ", "fal ", "fab ", "fad ",   # Font Awesome
    "glyphicon", "material-icons", "icon-", "bi-", "bi ",  # Bootstrap / Material / etc.
    "mdi-", "mdi ", "feather-", "heroicon",
    "sprite", "svg-icon", "icon icon", "ico-",
)

# Embedded media host patterns (iframe src)
YOUTUBE_PATTERN  = re.compile(r"youtube\.com|youtu\.be", re.I)
VIMEO_PATTERN    = re.compile(r"vimeo\.com", re.I)
WISTIA_PATTERN   = re.compile(r"wistia\.(com|net)", re.I)
LOOM_PATTERN     = re.compile(r"loom\.com", re.I)

# PDF magic bytes (first 4 bytes of every PDF file)
PDF_MAGIC = b"%PDF"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_IMAGE_EXT_RX = re.compile(r"\.(jpe?g|png|gif|webp|svg|avif|bmp|tiff?)$", re.I)

# Filler/CMS words that, joined with hyphens, make a slug rather than prose
# ("hero-banner-final"). Deliberately the same vocabulary as
# _AUTOGEN_FILENAME_RX's word list, checked per-segment rather than requiring
# the whole string to be one of these words plus a numeric suffix.
_FILLER_WORD_RX = re.compile(
    r"^(?:img|image|images|dsc|dscn|dscf|pxl|gopr|mvimg|pano|photo|pic|scan|"
    r"scanned|capture|screenshot|screen|snip|snap|untitled|unnamed|noname|new|"
    r"final|final2|finalfinal|copy|copyof|draft|download|downloaded|file|files|"
    r"upload|uploaded|attachment|asset|assets|hero|banner|bg|background|"
    r"placeholder|temp|tmp|test|output|export|render)$", re.I)


def _is_machine_formatted(alt: str) -> bool:
    """True when the alt reads like a file name rather than typed text: an
    image extension, a 3+ digit run, an underscore, a hyphenated slug where at
    least one segment is a filler/CMS word ('hero-banner-final'), or an
    auto-generated stem such as 'DSC_0042'.

    A no-space hyphenated string is NOT enough on its own -- ordinary compound
    words and brand names ('coca-cola', 'e-commerce', 'seven-eleven') are
    written exactly that way and must stay 'descriptive' even when they equal
    the file name."""
    s = alt.strip()
    bare = _IMAGE_EXT_RX.sub("", s)
    if _IMAGE_EXT_RX.search(s) or re.search(r"\d{3,}", s):
        return True
    if " " not in s and "_" in s:
        return True
    if _AUTOGEN_FILENAME_RX.match(bare):
        return True
    if " " not in s and "-" in s and s == s.lower():
        segs = [seg for seg in re.split(r"[-_.\s]+", bare) if seg]
        if any(_FILLER_WORD_RX.match(seg) for seg in segs):
            return True
    return False


def _classify_alt(alt_val, src=None) -> str:
    """Return one of: 'missing' | 'decorative' | 'generic' | 'descriptive'.

    An alt that is itself auto-generated-looking ('IMG_2041', 'hero-bg') is
    generic. When `src` is supplied, an alt that merely repeats the file name is
    generic only if it is also machine-formatted: alt="team_photo_02" on
    team_photo_02.jpg was copied from the file, but alt="Canva" on canva.png is
    a correct, human-written label for a logo. Short alts are not penalised just
    because the file name is a hash -- the alt is what the crawler reads."""
    if alt_val is None:
        return "missing"
    stripped = alt_val.strip()
    if stripped == "":
        return "decorative"
    low = stripped.lower()
    if low in GENERIC_ALT_TERMS or GENERIC_ALT_RX.match(low):
        return "generic"
    # Camera / CMS stems typed into the alt ('IMG_2041', 'DSC00192.jpg'). Needs
    # a digit, separator or extension so a long real word is never caught.
    bare = _IMAGE_EXT_RX.sub("", stripped)
    if (_AUTOGEN_FILENAME_RX.match(bare) and " " not in bare
            and (re.search(r"[\d_\-]", bare) or bare != stripped)):
        return "generic"
    if src:
        stem = _filename_stem(src).lower()
        if stem and _IMAGE_EXT_RX.sub("", low).strip() == stem and _is_machine_formatted(stripped):
            return "generic"
    return "descriptive"


def _snippet(tag: str, attrs: dict, max_len: int = 120) -> str:
    """Build a compact representative HTML snippet string for evidence."""
    parts = [f"<{tag}"]
    for k, v in attrs.items():
        if v is None:
            parts.append(f" {k}")
        else:
            v_display = v[:60] + "…" if len(v) > 60 else v
            parts.append(f' {k}="{v_display}"')
    parts.append(">")
    result = "".join(parts)
    return result[:max_len] + ("…" if len(result) > max_len else "")


def _is_icon_class(class_str: str) -> bool:
    c = class_str.lower()
    return any(frag in c for frag in ICON_CLASS_FRAGMENTS)


# ---------------------------------------------------------------------------
# HTML Parser
# ---------------------------------------------------------------------------

class NonTextMediaParser(HTMLParser):
    """
    Single-pass parser that classifies all non-text media into 6 categories.
    Tracks SVG depth to avoid double-counting nested SVG children.
    """

    def __init__(self):
        super().__init__()

        # category 1: standard images
        self.standard_images = []   # list of {alt_class, snippet, src_hint}

        # category 2: vector graphics (inline SVG)
        self.vector_graphics = []   # list of {accessible, method, snippet}

        # category 3: embedded media
        self.embedded_media  = []   # list of {kind, platform, has_caption_track, snippet}

        # category 4: canvas
        self.canvas_elements = []   # list of {has_fallback, snippet}

        # category 5: icon elements
        self.icon_elements   = []   # list of {properly_handled, method, snippet}

        # category 6: linked docs (PDF hrefs)
        self.pdf_links       = []   # list of href strings (deduplicated later)

        # category 7: a link/button whose ONLY accessible content is an <img>
        # with alt="" -- distinct from a merely-decorative empty alt (correct
        # when a link/button has other text, an aria-label, or a non-empty-alt
        # image alongside it). This is an objective WCAG 2.4.4/4.1.2 failure
        # ("link/button has no discernible text"), not a stylistic judgment
        # call: the element is unlabeled for a screen reader AND for any
        # non-visual AI crawler trying to understand navigation, since alt=""
        # instructs both to treat the image as if it were not there at all.
        self.unlabeled_interactive_images = []   # list of {tag, snippet}

        # --- internal state ---
        # Stack, not a flat flag, so a nested container (a <button> inside an
        # <a>, or vice versa -- unusual but not invalid to encounter in the
        # wild) is judged independently while text/images at any depth still
        # count toward EVERY enclosing container: a <button>Buy</button>
        # inside an <a> makes the outer <a> labeled too, even though "Buy" is
        # only a direct child of the inner element.
        self._interactive_stack = []
        self._svg_depth           = 0    # depth inside <svg> tags
        self._svg_has_title       = False
        self._svg_has_desc        = False
        self._svg_aria_label      = None
        self._svg_aria_labelledby = None
        self._svg_aria_hidden     = False
        self._svg_role            = None
        self._svg_snippet         = ""

        self._canvas_depth        = 0
        self._canvas_inner_words  = 0
        self._canvas_snippet      = ""

        self._in_video            = False
        self._video_has_track     = False
        self._video_snippet       = ""
        self._in_audio            = False
        self._audio_has_track     = False
        self._audio_snippet       = ""

        self._in_picture          = False  # inside <picture> wrapper

    # ---- helpers ----

    def _flush_svg(self):
        """Commit the completed <svg> to vector_graphics list."""
        accessible = (
            self._svg_has_title
            or self._svg_has_desc
            or bool(self._svg_aria_label)
            or bool(self._svg_aria_labelledby)
            or self._svg_aria_hidden   # deliberately hidden — correctly decorative
        )
        method = None
        if self._svg_aria_hidden:
            method = "aria-hidden (decorative)"
        elif self._svg_has_title:
            method = "<title>"
        elif self._svg_has_desc:
            method = "<desc>"
        elif self._svg_aria_label:
            method = "aria-label"
        elif self._svg_aria_labelledby:
            method = "aria-labelledby"
        self.vector_graphics.append({
            "accessible": accessible,
            "method": method,
            "snippet": self._svg_snippet,
        })

    def _flush_canvas(self, has_fallback: bool):
        self.canvas_elements.append({
            "has_fallback": has_fallback,
            "snippet": self._canvas_snippet,
        })

    # ---- tag handlers ----

    def handle_starttag(self, tag, attrs):
        tag_lower  = tag.lower()
        attrs_dict = {k.lower(): (v or "") for k, v in attrs}
        role       = attrs_dict.get("role", "").lower().strip()
        aria_hid   = attrs_dict.get("aria-hidden", "").lower().strip() == "true"

        # ---- category 1: <img> ----
        if tag_lower == "img":
            alt_val  = attrs_dict.get("alt") if "alt" in attrs_dict else None
            full_src = attrs_dict.get("src") or attrs_dict.get("data-src") or ""
            alt_cls  = _classify_alt(alt_val, full_src)
            src_hint = full_src[:80]
            self.standard_images.append({
                "alt_class": alt_cls,
                "filename_autogenerated": _is_autogenerated_filename(full_src),
                "snippet":   _snippet(tag_lower, {"src": src_hint, "alt": alt_val}),
                "src_hint":  src_hint,
            })
            # Propagate to every OPEN interactive container (see the stack
            # comment above for why this is "every", not just the innermost).
            # "generic"/"descriptive" alt still gives the element SOME
            # accessible name, even if the wording is poor -- that's a
            # separate finding (missing/generic alt) handled above. Both
            # "decorative" (alt="") and "missing" (no alt attribute at all)
            # provide NO accessible name, so either one leaves a link/button
            # unlabeled exactly the same way if nothing else does either.
            for entry in self._interactive_stack:
                if alt_cls in ("decorative", "missing"):
                    entry["has_unlabeled_img"] = True
                    if entry["unlabeled_alt_kind"] is None:
                        entry["unlabeled_alt_kind"] = alt_cls
                else:
                    entry["has_labeling_img"] = True

        # ---- category 1: <source> inside <picture> ----
        elif tag_lower == "source" and self._in_picture:
            # <source> elements inherit alt from the sibling <img> — tracked separately
            pass   # No independent alt; counted only when <img> is absent in picture

        elif tag_lower == "picture":
            self._in_picture = True

        # ---- category 2: <svg> ----
        elif tag_lower == "svg":
            if self._svg_depth == 0:
                # Start tracking the outermost SVG
                self._svg_has_title       = False
                self._svg_has_desc        = False
                self._svg_aria_label      = attrs_dict.get("aria-label", "")
                self._svg_aria_labelledby = attrs_dict.get("aria-labelledby", "")
                self._svg_aria_hidden     = aria_hid
                self._svg_role            = role
                self._svg_snippet         = _snippet(tag_lower, {
                    k: v for k, v in attrs_dict.items()
                    if k in ("class", "role", "aria-label", "aria-hidden", "aria-labelledby")
                })
            self._svg_depth += 1

        # ---- SVG child: <title> or <desc> ----
        elif tag_lower in ("title", "desc") and self._svg_depth > 0:
            if tag_lower == "title":
                self._svg_has_title = True
            else:
                self._svg_has_desc = True

        # ---- category 3: <video> ----
        elif tag_lower == "video":
            self._in_video       = True
            self._video_has_track = False
            self._video_snippet  = _snippet(tag_lower, {
                k: v for k, v in attrs_dict.items()
                if k in ("src", "controls", "aria-label", "title")
            })

        elif tag_lower == "track" and self._in_video:
            kind = attrs_dict.get("kind", "").lower()
            if kind in ("captions", "subtitles", "descriptions", ""):
                self._video_has_track = True
        elif tag_lower == "track" and self._in_audio:
            self._audio_has_track = True

        # ---- category 3: <audio> ----
        elif tag_lower == "audio":
            self._in_audio       = True
            self._audio_has_track = False
            self._audio_snippet  = _snippet(tag_lower, {
                k: v for k, v in attrs_dict.items()
                if k in ("src", "controls", "aria-label", "title")
            })

        # ---- category 3: <iframe> (embedded video platforms) ----
        elif tag_lower == "iframe":
            src = attrs_dict.get("src", "")
            if YOUTUBE_PATTERN.search(src):
                platform = "YouTube"
            elif VIMEO_PATTERN.search(src):
                platform = "Vimeo"
            elif WISTIA_PATTERN.search(src):
                platform = "Wistia"
            elif LOOM_PATTERN.search(src):
                platform = "Loom"
            else:
                platform = None

            if platform:
                title_attr = attrs_dict.get("title", "")
                aria_label = attrs_dict.get("aria-label", "")
                self.embedded_media.append({
                    "kind":              "iframe_video",
                    "platform":          platform,
                    "has_caption_track": False,      # iframes can't have <track>
                    "has_title_attr":    bool(title_attr.strip()),
                    "has_aria_label":    bool(aria_label.strip()),
                    "snippet":           _snippet(tag_lower, {
                        "src":        src[:70],
                        "title":      title_attr or None,
                        "aria-label": aria_label or None,
                    }),
                })

        # ---- category 4: <canvas> ----
        elif tag_lower == "canvas":
            self._canvas_depth   = 1
            self._canvas_inner_words = 0
            self._canvas_snippet = _snippet(tag_lower, {
                k: v for k, v in attrs_dict.items()
                if k in ("id", "class", "aria-label", "role")
            })

        # ---- category 5: icon elements ----
        # <i class="fa-..."> or <span class="icon-..."> or any element with role="img"
        elif tag_lower in ("i", "span") or role == "img":
            class_val = attrs_dict.get("class", "")
            is_icon   = _is_icon_class(class_val)
            if is_icon or role == "img":
                aria_label = attrs_dict.get("aria-label", "").strip()
                aria_lby   = attrs_dict.get("aria-labelledby", "").strip()
                title_attr = attrs_dict.get("title", "").strip()
                properly_handled = (
                    aria_hid
                    or bool(aria_label)
                    or bool(aria_lby)
                    or bool(title_attr)
                )
                if aria_hid:
                    method = "aria-hidden (decorative)"
                elif aria_label:
                    method = "aria-label"
                elif aria_lby:
                    method = "aria-labelledby"
                elif title_attr:
                    method = "title attribute"
                else:
                    method = None
                self.icon_elements.append({
                    "properly_handled": properly_handled,
                    "method":           method,
                    "snippet":          _snippet(tag_lower, {
                        "class":       class_val[:50] or None,
                        "role":        role or None,
                        "aria-label":  aria_label or None,
                        "aria-hidden": "true" if aria_hid else None,
                    }),
                })

        # ---- category 6: PDF links ----
        if tag_lower == "a":
            href = attrs_dict.get("href", "")
            if href:
                path = urllib.parse.urlparse(href).path.lower()
                if path.endswith(".pdf"):
                    self.pdf_links.append(href)

        # ---- category 7: track a candidate link/button for the unlabeled-
        # interactive-image check. An <a> with no href is a named anchor, not
        # a link, so it is not tracked; any <button> qualifies regardless.
        if (tag_lower == "a" and attrs_dict.get("href")) or tag_lower == "button":
            aria_label = attrs_dict.get("aria-label", "").strip()
            title_attr = attrs_dict.get("title", "").strip()
            self._interactive_stack.append({
                "tag": tag_lower,
                "has_text": False,
                "has_label": bool(aria_label) or bool(title_attr),
                "has_labeling_img": False,
                "has_unlabeled_img": False,
                "unlabeled_alt_kind": None,
                "snippet": _snippet(tag_lower, {
                    k: v for k, v in attrs_dict.items()
                    if k in ("href", "class", "aria-label", "title")
                }),
            })

    def handle_endtag(self, tag):
        tag_lower = tag.lower()

        if tag_lower == "picture":
            self._in_picture = False

        elif tag_lower == "svg" and self._svg_depth > 0:
            self._svg_depth -= 1
            if self._svg_depth == 0:
                self._flush_svg()

        elif tag_lower == "video" and self._in_video:
            self.embedded_media.append({
                "kind":              "video",
                "platform":          "native",
                "has_caption_track": self._video_has_track,
                "has_title_attr":    False,
                "has_aria_label":    False,
                "snippet":           self._video_snippet,
            })
            self._in_video = False

        elif tag_lower == "audio" and self._in_audio:
            self.embedded_media.append({
                "kind":              "audio",
                "platform":          "native",
                "has_caption_track": self._audio_has_track,
                "has_title_attr":    False,
                "has_aria_label":    False,
                "snippet":           self._audio_snippet,
            })
            self._in_audio = False

        elif tag_lower == "canvas" and self._canvas_depth > 0:
            self._canvas_depth = 0
            self._flush_canvas(has_fallback=(self._canvas_inner_words > 0))

        if (tag_lower in ("a", "button") and self._interactive_stack
                and self._interactive_stack[-1]["tag"] == tag_lower):
            entry = self._interactive_stack.pop()
            if (entry["has_unlabeled_img"] and not entry["has_text"]
                    and not entry["has_label"] and not entry["has_labeling_img"]):
                self.unlabeled_interactive_images.append({
                    "tag": entry["tag"],
                    "alt_kind": entry["unlabeled_alt_kind"],
                    "snippet": entry["snippet"],
                })

    def handle_data(self, data):
        if self._canvas_depth > 0 and data.strip():
            self._canvas_inner_words += len(data.split())
        if self._interactive_stack and data.strip():
            for entry in self._interactive_stack:
                entry["has_text"] = True


# ---------------------------------------------------------------------------
# PDF text-layer heuristic (stdlib only — no pypdf, no requests)
# ---------------------------------------------------------------------------

_PDF_TEXT_OP_RX   = re.compile(rb"BT\b[\s\S]{0,4000}?(?:Tj|TJ|'|\")")   # BT ... Tj/TJ
_PDF_STREAM_RX    = re.compile(rb"stream\r?\n([\s\S]*?)\r?\nendstream")
_PDF_MAX_STREAMS  = 25
_PDF_MAX_STREAM_BYTES = 3 * 1024 * 1024
_PDF_HARD_CEIL_BYTES  = 10 * 1024 * 1024

# Wall-clock ceiling across ALL linked-PDF inspections on one page. Every other
# network-bound script in this marketplace enforces one (check_sitemap.py 30s,
# check_page_speed_signals.py 20s, fetch_dual_identity.py 20s); this loop was
# the only one that did not, and a per-request `timeout` does not bound it: the
# socket timeout resets on every chunk that arrives, so a server trickling a
# 1 MB PDF a few bytes at a time never trips it and the audit hangs past the
# handout's <5 min runtime constraint. 25s is deliberately just above the
# nominal cost of the default 3 PDFs x 8s per-request timeout, so a healthy
# site's behaviour is completely unchanged -- this only ever fires on a
# pathologically slow host.
PDF_INSPECTION_DEADLINE_S = 25.0


def _scan_bytes_for_text_ops(buf: bytes) -> bool:
    if not buf:
        return False
    if _PDF_TEXT_OP_RX.search(buf):
        return True
    # positional text operators used without an explicit BT/ET wrapper in some writers
    return bool(re.search(rb"\b(Td|TD|Tf|Tj|TJ)\b", buf) and re.search(rb"\bTf\b", buf))


def inspect_pdf_stdlib(pdf_url: str, base_url: str, timeout: int = 8,
                       max_bytes: int = 1024 * 1024, gate=None) -> dict:
    """
    Fetches the first `max_bytes` (default 1 MB, hard ceiling 10 MB) of a PDF
    and decides whether it carries an extractable digital text layer.

    Detection order (first match wins):
      1. tagged-PDF structure  (/MarkInfo /Marked true  or  /StructTreeRoot)
      2. /ToUnicode CMap present (font-to-text mapping -> real selectable text)
      3. uncompressed text-drawing operators in the raw bytes  (BT ... Tj/TJ)
      4. FlateDecode (zlib) content streams inflated, then scanned for the
         same text operators  -- this is what the old byte-header heuristic
         missed, since almost every real PDF Flate-compresses its content
      5. /Subtype /Image XObject present and NO text operators anywhere
         -> image-only / scanned  (has_text_layer = False)
      6. otherwise, if the fetch was truncated -> None (inconclusive), never a
         false "no text layer"
    """
    abs_url = urllib.parse.urljoin(base_url, pdf_url) if base_url else pdf_url
    max_bytes = max(64 * 1024, min(int(max_bytes), _PDF_HARD_CEIL_BYTES))
    result  = {
        "url":               abs_url,
        "http_status":       None,
        "byte_size_fetched": None,
        "has_text_layer":    None,
        "method":            None,
        "streams_found":     0,
        "streams_inflated":  0,
        "truncated":         None,
        "error":             None,
    }
    try:
        req = urllib.request.Request(
            abs_url,
            headers={
                "User-Agent": "Mozilla/5.0 (compatible; BrandAIAuditor/2.0)",
                "Range":      f"bytes=0-{max_bytes - 1}",
            }
        )
        # Read in chunks against a wall-clock budget rather than one blocking
        # `resp.read(max_bytes)`. The socket `timeout` only bounds the gap
        # BETWEEN chunks -- it resets every time a byte arrives -- so a host
        # trickling a 1 MB PDF a few bytes at a time never trips it and this
        # single call would hang indefinitely, taking the whole audit past the
        # <5 min runtime constraint with it. `read1` returns whatever has
        # actually arrived instead of blocking for a full buffer, so the
        # deadline below is checked promptly rather than once per 64 KB.
        _read_start = time.time()
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            result["http_status"] = resp.status
            _read1 = getattr(resp, "read1", None) or resp.read
            chunks, got = [], 0
            while got < max_bytes:
                if time.time() - _read_start > timeout:
                    result["read_deadline_exceeded"] = True
                    break
                chunk = _read1(min(65536, max_bytes - got))
                if not chunk:
                    break
                chunks.append(chunk)
                got += len(chunk)
            raw = b"".join(chunks)
        result["byte_size_fetched"] = len(raw)
        # A budget-truncated read is truncated in the same sense as a
        # size-truncated one: downstream must treat an inconclusive scan as
        # has_text_layer=None, never as "this PDF has no text layer".
        result["truncated"] = len(raw) >= max_bytes or bool(result.get("read_deadline_exceeded"))

        if not raw.startswith(PDF_MAGIC):
            result["error"] = "Response does not start with PDF magic bytes (%PDF)"
            result["has_text_layer"] = False
            result["method"] = "not_a_pdf"
            return result

        # 1. tagged PDF structure
        if re.search(rb"/MarkInfo\b[\s\S]{0,60}/Marked\s*/?true", raw) or \
           re.search(rb"/StructTreeRoot\b", raw):
            result["has_text_layer"] = True
            result["method"] = "tagged_structure"
            return result

        # 2. font-to-unicode mapping
        if re.search(rb"/ToUnicode\b", raw):
            result["has_text_layer"] = True
            result["method"] = "tounicode_cmap"
            return result

        # 3. uncompressed text operators
        if _scan_bytes_for_text_ops(raw):
            result["has_text_layer"] = True
            result["method"] = "uncompressed_text_operators"
            return result

        # 4. inflate FlateDecode streams and scan
        streams = _PDF_STREAM_RX.findall(raw)
        result["streams_found"] = len(streams)
        inflated = 0
        for s in streams[:_PDF_MAX_STREAMS]:
            if not s or len(s) > _PDF_MAX_STREAM_BYTES:
                continue
            for wbits in (15, -15, 47):
                try:
                    dec = zlib.decompress(s, wbits)
                except Exception:
                    continue
                inflated += 1
                if _scan_bytes_for_text_ops(dec):
                    result["streams_inflated"] = inflated
                    result["has_text_layer"] = True
                    result["method"] = "flate_decoded_text_operators"
                    return result
                break
        result["streams_inflated"] = inflated

        # 5. image XObject present, no text found anywhere
        if re.search(rb"/Subtype\s*/Image\b", raw):
            if result["truncated"]:
                result["has_text_layer"] = None
                result["method"] = "image_xobject_no_text_but_truncated"
            else:
                result["has_text_layer"] = False
                result["method"] = "image_xobject_no_text"
            return result

        # 6. inconclusive
        if result["truncated"]:
            result["has_text_layer"] = None
            result["method"] = "inconclusive_truncated"
        else:
            result["has_text_layer"] = False
            result["method"] = "no_text_operators_found"
        return result

    except urllib.error.HTTPError as e:
        result["http_status"] = e.code
        result["error"]       = f"HTTP {e.code}"
    except Exception as e:
        result["error"] = str(e)[:120]
    return result


# ---------------------------------------------------------------------------
# Main audit function
# ---------------------------------------------------------------------------

def check_nontext_facts(html_content: str, url: str = "", max_pdfs: int = 3, robots=None) -> dict:
    parser = NonTextMediaParser()
    try:
        parser.feed(html_content or "")
    except Exception:
        pass

    # ---- 1. Standard images ----
    imgs = parser.standard_images
    img_total       = len(imgs)
    img_missing     = sum(1 for i in imgs if i["alt_class"] == "missing")
    img_decorative  = sum(1 for i in imgs if i["alt_class"] == "decorative")
    img_generic     = sum(1 for i in imgs if i["alt_class"] == "generic")
    img_descriptive = sum(1 for i in imgs if i["alt_class"] == "descriptive")
    img_autogen_fn  = sum(1 for i in imgs if i.get("filename_autogenerated"))
    # Representative snippet of first missing-alt image
    first_missing_img_snippet = next(
        (i["snippet"] for i in imgs if i["alt_class"] == "missing"), None
    )
    first_generic_img_snippet = next(
        (i["snippet"] for i in imgs if i["alt_class"] == "generic"), None
    )

    # ---- 2. Vector graphics ----
    svgs = parser.vector_graphics
    svg_total       = len(svgs)
    svg_accessible  = sum(1 for s in svgs if s["accessible"])
    svg_inaccessible = svg_total - svg_accessible
    first_bad_svg_snippet = next(
        (s["snippet"] for s in svgs if not s["accessible"]), None
    )

    # ---- 3. Embedded media ----
    media = parser.embedded_media
    videos          = [m for m in media if m["kind"] == "video"]
    audios          = [m for m in media if m["kind"] == "audio"]
    iframe_videos   = [m for m in media if m["kind"] == "iframe_video"]
    video_no_cap    = [v for v in videos    if not v["has_caption_track"]]
    audio_no_cap    = [a for a in audios    if not a["has_caption_track"]]
    iframe_no_title = [i for i in iframe_videos if not i["has_title_attr"] and not i["has_aria_label"]]
    first_video_snippet       = videos[0]["snippet"]       if videos else None
    first_iframe_snippet      = iframe_videos[0]["snippet"] if iframe_videos else None

    # ---- 4. Canvas ----
    canvases        = parser.canvas_elements
    canvas_total    = len(canvases)
    canvas_no_fallback = sum(1 for c in canvases if not c["has_fallback"])
    first_canvas_snippet = canvases[0]["snippet"] if canvases else None

    # ---- 5. Icon elements ----
    icons           = parser.icon_elements
    icon_total      = len(icons)
    icon_ok         = sum(1 for ic in icons if ic["properly_handled"])
    icon_unlabelled = icon_total - icon_ok
    first_bad_icon_snippet = next(
        (ic["snippet"] for ic in icons if not ic["properly_handled"]), None
    )

    # ---- 6. Linked PDFs ----
    seen_pdfs = []
    seen_set  = set()
    for h in parser.pdf_links:
        if h not in seen_set:
            seen_set.add(h)
            seen_pdfs.append(h)

    pdf_results = []
    # Downloading a linked PDF is a fetch of that URL; sites commonly disallow
    # /files/ or /wp-content/uploads/ precisely to keep crawlers out of them.
    _gate = RobotsGate.for_url(url, robots=robots) if RobotsGate else None
    _pdf_start = time.time()
    for href in seen_pdfs[:max_pdfs]:
        if _gate is not None:
            _decision = _gate.allows(href, "*")
            if not _decision.allowed:
                pdf_results.append({"url": href, "skipped_by_robots": True,
                                    "has_text_layer": None, "error": _decision.reason})
                continue
        _left = PDF_INSPECTION_DEADLINE_S - (time.time() - _pdf_start)
        if _left <= 1.0:
            # Budget spent. Report the PDF as NOT MEASURED (has_text_layer stays
            # None), never as "no text layer" -- an unread PDF is not a defect.
            pdf_results.append({
                "url": href, "has_text_layer": None, "deadline_exceeded": True,
                "error": f"skipped: {PDF_INSPECTION_DEADLINE_S:.0f}s PDF-inspection budget exceeded"})
            continue
        pdf_results.append(inspect_pdf_stdlib(
            href, url, timeout=int(max(2, min(8, _left))), gate=_gate))

    pdf_no_text = [p for p in pdf_results if p.get("has_text_layer") is False]

    # ---- Aggregate accessibility scores ----
    images_without_alt_count = img_missing + img_generic   # combined problem count

    return {
        # Legacy flat key kept for backward-compat with older synthesize_report check
        "images_without_alt_count": images_without_alt_count,

        # ---- Category 1 ----
        "standard_images": {
            "total":                      img_total,
            "missing_alt":                img_missing,
            "decorative_alt_empty":       img_decorative,
            "generic_alt_placeholder":    img_generic,
            "descriptive_alt":            img_descriptive,
            "autogenerated_filename_count": img_autogen_fn,
            "first_missing_alt_snippet":  first_missing_img_snippet,
            "first_generic_alt_snippet":  first_generic_img_snippet,
        },

        # ---- Category 2 ----
        "vector_graphics": {
            "total":                      svg_total,
            "accessible":                 svg_accessible,
            "inaccessible":               svg_inaccessible,
            "first_inaccessible_snippet": first_bad_svg_snippet,
        },

        # ---- Category 3 ----
        "embedded_media": {
            "video_total":                len(videos),
            "video_missing_captions":     len(video_no_cap),
            "audio_total":                len(audios),
            "audio_missing_captions":     len(audio_no_cap),
            "iframe_video_total":         len(iframe_videos),
            "iframe_video_missing_title": len(iframe_no_title),
            "first_video_snippet":        first_video_snippet,
            "first_iframe_snippet":       first_iframe_snippet,
        },

        # ---- Category 4 ----
        "canvas_and_interactive": {
            "total":               canvas_total,
            "missing_fallback":    canvas_no_fallback,
            "first_snippet":       first_canvas_snippet,
        },

        # ---- Category 5 ----
        "icon_elements": {
            "total":               icon_total,
            "properly_handled":    icon_ok,
            "unlabelled":          icon_unlabelled,
            "first_bad_snippet":   first_bad_icon_snippet,
        },

        # ---- Category 6 ----
        "linked_documents": {
            "pdf_links_found":     len(seen_pdfs),
            "pdf_links_inspected": len(pdf_results),
            "pdf_missing_text_layer": len(pdf_no_text),
            "details":             pdf_results,
        },

        # ---- Category 7 ----
        # A link/button whose ONLY content is an <img> with alt="" (or no alt
        # at all) and no other text/aria-label/title/labeling-image alongside
        # it. Distinct from `standard_images.decorative_alt_empty`, which
        # counts EVERY alt="" image, most of which are correctly decorative
        # (a spacer, a background flourish) -- flagging all of those would be
        # a false-positive generator penalising sites for following W3C
        # guidance. This category is narrower and unambiguous: the element
        # has no accessible name at all, an objective WCAG 2.4.4/4.1.2
        # failure, not a stylistic judgment call.
        "unlabeled_interactive_images": {
            "count":   len(parser.unlabeled_interactive_images),
            "details": parser.unlabeled_interactive_images[:10],
        },
    }


# ---------------------------------------------------------------------------
# Entry-point
# ---------------------------------------------------------------------------

import threading


def read_stdin_safe(timeout: float = 0.2) -> str:
    if sys.stdin.isatty():
        return ""
    res = []
    def _target():
        try:
            res.append(sys.stdin.read())
        except Exception:
            pass
    t = threading.Thread(target=_target, daemon=True)
    t.start()
    t.join(timeout=timeout)
    return res[0].lstrip("\ufeff") if res else ""


if __name__ == "__main__":
    try:
        html_content = ""
        url          = ""
        params       = {}

        if len(sys.argv) > 1:
            raw_arg = sys.argv[1].strip()
            if raw_arg.startswith("{"):
                try:
                    params       = json.loads(raw_arg)
                    html_content = params.get("html", "") or params.get("raw_html", "")
                    url          = params.get("url", "")
                except json.JSONDecodeError:
                    url = raw_arg
            else:
                url = raw_arg

        input_data = read_stdin_safe(timeout=1.0 if len(sys.argv) > 1 else 5.0)
        if input_data.strip():
            try:
                sp = json.loads(input_data)
                if isinstance(sp, dict):
                    params.update(sp)
            except json.JSONDecodeError:
                pass

        if not html_content:
            html_content = params.get("html", "") or params.get("raw_html", "")
        if not url:
            url = params.get("url", "")

        result = check_nontext_facts(html_content, url, robots=params.get("robots"))
        print(json.dumps(result, indent=2))
    except Exception as e:
        print(json.dumps({"error": f"Script execution failed: {str(e)}"}))

